CREATE DATABASE Acadamy_318_SQL
ON
(
NAME = Acadamy_318_SQL,
FILENAME = 'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Acadamy_318_SQL.mdf',
SIZE = 8 MB,
MAXSIZE = 500 MB,
FILEGROWTH = 8 MB
)
LOG ON
(
NAME = Acadamy_318_SQL_Log,
FILENAME = 'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Acadamy_318_SQL.ldf',
SIZE = 8 MB,
MAXSIZE = 500 MB,
FILEGROWTH = 8 MB
)